apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: cop-classifier
spec:
  replicas: 2
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: cop-classifier
        image: gcr.io/my-website-169905/cop-classifier:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
